language: node_js
sudo: false
cache:
  directories:
  - node_modules
env:
  global:
    - NODE_ENV=production
    - CFDISTRO=your_cf_distro_id_here
script:
  - npm run lint
  - npm test
before_deploy:
  - npm run compile
  - mkdir -p dist
  - cp index-prod.html dist/index.html
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - |
    aws s3api create-bucket \
      --acl public-read \
      --bucket react-redux-boilerplate.bjacobel.com \
      --region us-east-1
  - |
    aws s3 website s3://react-redux-boilerplate.bjacobel.com/ \
      --index-document index.html \
      --error-document error.html
deploy:
  provider: s3
  region: us-east-1
  bucket: react-redux-boilerplate.bjacobel.com
  acl: public_read
  local_dir: dist
  skip_cleanup: true
  on:
    branch: master
after_deploy:
  - aws configure set preview.cloudfront true
  - |
    aws cloudfront create-invalidation \
      --distribution-id $CFDISTRO \
      --paths /index.html /main.js
